language: generic

services:
  - docker

script:
  - make

deploy:
  provider: script
  script: make push
  on:
    branch: master

env:
  global:
    secure: "QlNfVHp6wxjJIdnvuFmTyg26+1zIDJjoiU2vwBIome1ppqKK8Y6kdxIzhfRqN8Pu+v/Uwf02NvPGFpb56+wpCKGhb9ifFJxvqIlx2Fm2U++bPlIa4KLrqXKDgPI14uf4it5GVFGRNOWGUB1br6aF6+YssPgy6gpettA3LDwCqnole2kQlcQCG8zbgs8J5S0xvpis3jL/Ju1NxPXOC5eLxiCJj47xgdI0e+s5jokheXu1+OFFgMHyIB7YeQkSU68Idv2/Ls8CcWKY1hRxY8GFIeKonIfypQF3qZdMLwlMz5N1VSkJsk2ywhd5lGkGgsfvQjSdbIPNBzIyPHl3cqss0y+NjOmHbGoix/BENH+Sa/ZlRdDijq5Uc538SARcsSLM3BHeMqVCYKpMhs24Sy6RW4LgWDK4zQN7IDeLnu5Ga7ONpqGrqeD+JmzD4yihfWJ2H3EElCrc8voa5S/9jwdoGksNIbhauiWl6TBdTplui+Yi+BZ3mzpEWVXefnyCGuKh55i4mc+qkogbzmTP/3ZDkWVzYjOP02ZTUirggxKjR+6PhT346FAQ7n9flcuG0+cjoObAMnqLepr+aWG/EMON0bCU/cFwtyTHtsh8x0yIfZ/5qi9qI+veLbx267Kzw3PBA1FUORrGTlJdA+ZCT5bV9bTmVCl0Y136HE32j2L55U0="
