language: generic

services:
  - docker

script:
  - docker build -t psliwka/aptly .

deploy:
  provider: script
  script:
    - printenv "DOCKER_PASSWORD" | docker login -u "psliwkadeploys" --password-stdin
    - docker push psliwka/aptly
  on:
    branch: master

env:
  global:
    secure: ddFX6+vWW55hgcTFL+jDgen6/7WSmIllZNAL2m0PTImgAuJ/h3WhEdAzotUCl6/GV1u1Uidw8X2D5FhgX0TS2lR9hX8zRB8i6sSTk44uvu2QY8IgOXyNDYvUZk4XRQVARBbaZ+FD9CAQRBUIx5+3wvz3iTIkJF5nfT7BUOrldzV4118lBS05DH4/fyhsO6O2fZJkScyIC7QkDxvgSvJc3MRs6SgOuvCSMet3a5uWF4TLykAeQ4AAp8zsqYshK0UkVMBIPMO4BXVciiM855GC5boYHbl9VQ2lb+36DNaBdghdVgxmamvk8nRtQ33g0oJh4lc+9X3gBYZcNhfPip5YvMHUCpMWUBUuFRVgsbaV9mTvgYGDOnaEaRAorZvThkx0e17wBg+N0AZ3zkvHYmcuvb0xKO5Bc7RxwADk7/zTFdzs5pHZS90q5/Xyw5v8ZQFcLOua7Qjo3UubmVG58hfLViN8fCUBpJPjeVZgL8josTv1oj4dFrgw8duh0j3u/TL1nKM+xgCGvXP1C7caPr059hro6bCf9m2k+Dm0ITwdbvrFxEUt66HCGabQxeys/o1Lg2MwxEKO328VrEw6ccjrueekr6woyJoZUBmoSbgLM6bFlYz8sc5NqYBcI+nLI6csiVsqgLNiPozUJ5OooopJhM83SvnFscnkuA/FYCTyj9Q=
